### ISSUE TITLE
5 CSS methodologies you need to know in 2022 - Article Submission

### ISSUE THREAD

**Issue by RainboeStrykr** [genicsblog/genicsblog.github.io#62]
### Idea
Until CSS gets its own native scoping mechanism, we need to devise our own system for locking down styles to specific sections of an HTML document. CSS methodologies are the solution.

### Topics

**Category**: web

**Tags**: CSS, beginners, web-development

### Cross-posting?

No

**Comment by gouravkhunger** [comment]
Good article idea! Seems interesting to me.

Here are the next steps to post an article:

- Getting the first draft ready. You can use any markdown app you like. Here are the [UI elements](https://docs.genicsblog.com/author/ui-components) that Genics supports.
- Once you are happy with the draft and want to submit it, you can create a file in the `_drafts` folder, [here's a guide](https://docs.genicsblog.com/author/writing-the-article) to help you with it.
- Once you make a valid PR for the draft, you're done! We will review the article and publish it within a day of draft submission.
- Since this is an original post, you are eligible for 2 backlinks, will get back to you on this same issue once the draft is reviewed, so that we can provide dofollow backlinks to your suggested links.

And again, if you're stuck at any step, you can add a comment here! Looking forward to your first contribution to the blog 😄

**Comment by gouravkhunger** [comment]
Thanks for submitting [the draft](https://genicsblog.com/draft/five-css-methodologies-you-need-to-know-in-2022) @RainboeStrykr! It's not indexed and not visible unless someone has the link.

We'll go through it, and perform the basic formatting edits(if any) for you, and we'll leave a review here in the comments. There's no action needed in your part for now. Congrats on submitting your first draft!

**Comment by gouravkhunger** [comment]
Can you please confirm if you have the rights for the cover image you used? We can't copy-paste someone else's image, so if you have any licensable image, we'll happily keep it on the cover! If you wish to keep the current one, we'll have to [add a notice](https://docs.genicsblog.com/author/writing-the-article#optional-values) on top of the post.

**Comment by RainboeStrykr** [comment]
I do not have the rights to that image. 
I have created a new banner which I have the rights to
https://abhiraj-is.super-cool.xyz/css-methodologies.png

**Comment by Tabadia** [comment]
Love the formatting and content, looks great! 
I love how it gets to the point quickly, and its very imformative.

Only typo I noticed:
![image](https://user-images.githubusercontent.com/77317793/150454124-124e3837-c660-4631-afa1-ebabcbe9c86b.png)
*visual properties

**Comment by gouravkhunger** [comment]
Hey @RainboeStrykr we've done the basic editing and your post is live now!

Link: https://genicsblog.com/five-css-methodologies-you-need-to-know-in-2022

Congrats on getting your first article published! If you need further support regarding the article, you can get in touch on the discord server :)
