### ISSUE TITLE
Post idea: How to make a REST API using NodeJS and MongoDB

### ISSUE THREAD

**Issue by Kira272921** [genicsblog/genicsblog.github.io#66]
### Idea

A blog post about how to create a REST API using NodeJS and MongoDB from start till deployment! 🚀

### Topics

**Category**:  web

**Tags**: API, Backend, Beginners

### Cross-posting?

https://kirablog.hashnode.dev/rest-api-using-nodejs

**Comment by gouravkhunger** [comment]
Hey! Thanks for the submission request. You can create a draft post for the same. [Here are the docs](https://docs.genicsblog.com/author/writing-the-article) to help you out.

Do remember to fetch upstream before proceeding. Make your changes in a new branch in your fork, so that your main remains clean. Since #65 was created from commits in your main, it's now behind the main branch.

I know this can be a bit confusing, if you need help ping us in the discord server 😄

**Comment by gouravkhunger** [comment]
[Your post](https://genicsblog.com/kira/how-to-build-a-rest-api-using-nodejs) is published! Congrats :)
